[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.0"


[workspace]
members = ["programs/cp-swap"]

[features]
seeds = false
skip-lint = false

[programs.Localnet]
soldium = "6Hf5A4pofi7DjWAvWNMA5R7RyueFqPGYptt2jS4hCt5L"


[registry]
url = "https://github.com/raydium-io/raydium-cp-swap"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://solana-mainnet.core.chainstack.com/a5d983e71c3e60493d22234ea66ce125"


